export const hiraganaData = {
  basic: {
    "a-line": [
      {
        romaji: "a",
        hiragana: "あ",
        pronounce: "/music/a.mp3",
        difficulty: 1,
        category: "vowel",
      },
      {
        romaji: "i",
        hiragana: "い",
        pronounce: "/music/i.mp3",
        difficulty: 1,
        category: "vowel",
      },
      {
        romaji: "u",
        hiragana: "う",
        pronounce: "/music/u.mp3",
        difficulty: 1,
        category: "vowel",
      },
      {
        romaji: "e",
        hiragana: "え",
        pronounce: "/music/e.mp3",
        difficulty: 1,
        category: "vowel",
      },
      {
        romaji: "o",
        hiragana: "お",
        pronounce: "/music/o.mp3",
        difficulty: 1,
        category: "vowel",
      },
    ],
    "ka-line": [
      {
        romaji: "ka",
        hiragana: "か",
        pronounce: "/music/ka.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "ki",
        hiragana: "き",
        pronounce: "/music/ki.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "ku",
        hiragana: "く",
        pronounce: "/music/ku.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "ke",
        hiragana: "け",
        pronounce: "/music/ke.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "ko",
        hiragana: "こ",
        pronounce: "/music/ko.mp3",
        difficulty: 2,
        category: "consonant",
      },
    ],
    "sa-line": [
      {
        romaji: "sa",
        hiragana: "さ",
        pronounce: "/music/sa.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "shi",
        hiragana: "し",
        pronounce: "/music/shi.mp3",
        difficulty: 3,
        category: "special",
      },
      {
        romaji: "su",
        hiragana: "す",
        pronounce: "/music/su.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "se",
        hiragana: "せ",
        pronounce: "/music/se.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "so",
        hiragana: "そ",
        pronounce: "/music/so.mp3",
        difficulty: 2,
        category: "consonant",
      },
    ],
    "ta-line": [
      {
        romaji: "ta",
        hiragana: "た",
        pronounce: "/music/ta.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "chi",
        hiragana: "ち",
        pronounce: "/music/chi.mp3",
        difficulty: 3,
        category: "special",
      },
      {
        romaji: "tsu",
        hiragana: "つ",
        pronounce: "/music/tsu.mp3",
        difficulty: 4,
        category: "special",
      },
      {
        romaji: "te",
        hiragana: "て",
        pronounce: "/music/te.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "to",
        hiragana: "と",
        pronounce: "/music/to.mp3",
        difficulty: 2,
        category: "consonant",
      },
    ],
    "na-line": [
      {
        romaji: "na",
        hiragana: "な",
        pronounce: "/music/na.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "ni",
        hiragana: "に",
        pronounce: "/music/ni.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "nu",
        hiragana: "ぬ",
        pronounce: "/music/nu.mp3",
        difficulty: 3,
        category: "consonant",
      },
      {
        romaji: "ne",
        hiragana: "ね",
        pronounce: "/music/ne.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "no",
        hiragana: "の",
        pronounce: "/music/no.mp3",
        difficulty: 2,
        category: "consonant",
      },
    ],
    "ha-line": [
      {
        romaji: "ha",
        hiragana: "は",
        pronounce: "/music/ha.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "hi",
        hiragana: "ひ",
        pronounce: "/music/hi.mp3",
        difficulty: 3,
        category: "consonant",
      },
      {
        romaji: "fu",
        hiragana: "ふ",
        pronounce: "/music/fu.mp3",
        difficulty: 3,
        category: "special",
      },
      {
        romaji: "he",
        hiragana: "へ",
        pronounce: "/music/he.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "ho",
        hiragana: "ほ",
        pronounce: "/music/ho.mp3",
        difficulty: 2,
        category: "consonant",
      },
    ],
    "ma-line": [
      {
        romaji: "ma",
        hiragana: "ま",
        pronounce: "/music/ma.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "mi",
        hiragana: "み",
        pronounce: "/music/mi.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "mu",
        hiragana: "む",
        pronounce: "/music/mu.mp3",
        difficulty: 3,
        category: "consonant",
      },
      {
        romaji: "me",
        hiragana: "め",
        pronounce: "/music/me.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "mo",
        hiragana: "も",
        pronounce: "/music/mo.mp3",
        difficulty: 2,
        category: "consonant",
      },
    ],
    "ya-line": [
      {
        romaji: "ya",
        hiragana: "や",
        pronounce: "/music/ya.mp3",
        difficulty: 2,
        category: "consonant",
      },
      null,
      {
        romaji: "yu",
        hiragana: "ゆ",
        pronounce: "/music/yu.mp3",
        difficulty: 2,
        category: "consonant",
      },
      null,
      {
        romaji: "yo",
        hiragana: "よ",
        pronounce: "/music/yo.mp3",
        difficulty: 2,
        category: "consonant",
      },
    ],
    "ra-line": [
      {
        romaji: "ra",
        hiragana: "ら",
        pronounce: "/music/ra.mp3",
        difficulty: 3,
        category: "consonant",
      },
      {
        romaji: "ri",
        hiragana: "り",
        pronounce: "/music/ri.mp3",
        difficulty: 3,
        category: "consonant",
      },
      {
        romaji: "ru",
        hiragana: "る",
        pronounce: "/music/ru.mp3",
        difficulty: 3,
        category: "consonant",
      },
      {
        romaji: "re",
        hiragana: "れ",
        pronounce: "/music/re.mp3",
        difficulty: 3,
        category: "consonant",
      },
      {
        romaji: "ro",
        hiragana: "ろ",
        pronounce: "/music/ro.mp3",
        difficulty: 3,
        category: "consonant",
      },
    ],
    "wa-line": [
      {
        romaji: "wa",
        hiragana: "わ",
        pronounce: "/music/wa.mp3",
        difficulty: 2,
        category: "consonant",
      },
      null,
      null,
      null,
      {
        romaji: "wo",
        hiragana: "を",
        pronounce: "/music/wo.mp3",
        difficulty: 4,
        category: "special",
      },
    ],
    n: [
      {
        romaji: "n",
        hiragana: "ん",
        pronounce: "/music/n.mp3",
        difficulty: 3,
        category: "special",
      },
    ],
  },
  voiced: {
    "ga-line": [
      {
        romaji: "ga",
        hiragana: "が",
        pronounce: "/music/ga.mp3",
        difficulty: 3,
        category: "voiced",
      },
      {
        romaji: "gi",
        hiragana: "ぎ",
        pronounce: "/music/gi.mp3",
        difficulty: 3,
        category: "voiced",
      },
      {
        romaji: "gu",
        hiragana: "ぐ",
        pronounce: "/music/gu.mp3",
        difficulty: 3,
        category: "voiced",
      },
      {
        romaji: "ge",
        hiragana: "げ",
        pronounce: "/music/ge.mp3",
        difficulty: 3,
        category: "voiced",
      },
      {
        romaji: "go",
        hiragana: "ご",
        pronounce: "/music/go.mp3",
        difficulty: 3,
        category: "voiced",
      },
    ],
    "za-line": [
      {
        romaji: "za",
        hiragana: "ざ",
        pronounce: "/music/za.mp3",
        difficulty: 3,
        category: "voiced",
      },
      {
        romaji: "ji",
        hiragana: "じ",
        pronounce: "/music/ji.mp3",
        difficulty: 4,
        category: "voiced",
      },
      {
        romaji: "zu",
        hiragana: "ず",
        pronounce: "/music/zu.mp3",
        difficulty: 3,
        category: "voiced",
      },
      {
        romaji: "ze",
        hiragana: "ぜ",
        pronounce: "/music/ze.mp3",
        difficulty: 3,
        category: "voiced",
      },
      {
        romaji: "zo",
        hiragana: "ぞ",
        pronounce: "/music/zo.mp3",
        difficulty: 3,
        category: "voiced",
      },
    ],
    "da-line": [
      {
        romaji: "da",
        hiragana: "だ",
        pronounce: "/music/da.mp3",
        difficulty: 3,
        category: "voiced",
      },
      {
        romaji: "ji",
        hiragana: "ぢ",
        pronounce: "/music/dji.mp3",
        difficulty: 5,
        category: "voiced",
      },
      {
        romaji: "dzu",
        hiragana: "づ",
        pronounce: "/music/dzu.mp3",
        difficulty: 5,
        category: "voiced",
      },
      {
        romaji: "de",
        hiragana: "で",
        pronounce: "/music/de.mp3",
        difficulty: 3,
        category: "voiced",
      },
      {
        romaji: "do",
        hiragana: "ど",
        pronounce: "/music/do.mp3",
        difficulty: 3,
        category: "voiced",
      },
    ],
    "ba-line": [
      {
        romaji: "ba",
        hiragana: "ば",
        pronounce: "/music/ba.mp3",
        difficulty: 3,
        category: "voiced",
      },
      {
        romaji: "bi",
        hiragana: "び",
        pronounce: "/music/bi.mp3",
        difficulty: 3,
        category: "voiced",
      },
      {
        romaji: "bu",
        hiragana: "ぶ",
        pronounce: "/music/bu.mp3",
        difficulty: 3,
        category: "voiced",
      },
      {
        romaji: "be",
        hiragana: "べ",
        pronounce: "/music/be.mp3",
        difficulty: 3,
        category: "voiced",
      },
      {
        romaji: "bo",
        hiragana: "ぼ",
        pronounce: "/music/bo.mp3",
        difficulty: 3,
        category: "voiced",
      },
    ],
    "pa-line": [
      {
        romaji: "pa",
        hiragana: "ぱ",
        pronounce: "/music/pa.mp3",
        difficulty: 4,
        category: "voiced",
      },
      {
        romaji: "pi",
        hiragana: "ぴ",
        pronounce: "/music/pi.mp3",
        difficulty: 4,
        category: "voiced",
      },
      {
        romaji: "pu",
        hiragana: "ぷ",
        pronounce: "/music/pu.mp3",
        difficulty: 4,
        category: "voiced",
      },
      {
        romaji: "pe",
        hiragana: "ぺ",
        pronounce: "/music/pe.mp3",
        difficulty: 4,
        category: "voiced",
      },
      {
        romaji: "po",
        hiragana: "ぽ",
        pronounce: "/music/po.mp3",
        difficulty: 4,
        category: "voiced",
      },
    ],
  },
};
