export const hiraganaData = {
  basic: {
    "a-line": [
      {
        romaji: "a",
        hiragana: "あ",
        pronounce: "/audio/hiragana/a.mp3",
        difficulty: 1,
        category: "vowel",
      },
      {
        romaji: "i",
        hiragana: "い",
        pronounce: "/audio/hiragana/i.mp3",
        difficulty: 1,
        category: "vowel",
      },
      {
        romaji: "u",
        hiragana: "う",
        pronounce: "/audio/hiragana/u.mp3",
        difficulty: 1,
        category: "vowel",
      },
      {
        romaji: "e",
        hiragana: "え",
        pronounce: "/audio/hiragana/e.mp3",
        difficulty: 1,
        category: "vowel",
      },
      {
        romaji: "o",
        hiragana: "お",
        pronounce: "/audio/hiragana/o.mp3",
        difficulty: 1,
        category: "vowel",
      },
    ],
    "ka-line": [
      {
        romaji: "ka",
        hiragana: "か",
        pronounce: "/audio/hiragana/ka.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "ki",
        hiragana: "き",
        pronounce: "/audio/hiragana/ki.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "ku",
        hiragana: "く",
        pronounce: "/audio/hiragana/ku.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "ke",
        hiragana: "け",
        pronounce: "/audio/hiragana/ke.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "ko",
        hiragana: "こ",
        pronounce: "/audio/hiragana/ko.mp3",
        difficulty: 2,
        category: "consonant",
      },
    ],
    "sa-line": [
      {
        romaji: "sa",
        hiragana: "さ",
        pronounce: "/audio/hiragana/sa.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "shi",
        hiragana: "し",
        pronounce: "/audio/hiragana/shi.mp3",
        difficulty: 3,
        category: "special",
      },
      {
        romaji: "su",
        hiragana: "す",
        pronounce: "/audio/hiragana/su.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "se",
        hiragana: "せ",
        pronounce: "/audio/hiragana/se.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "so",
        hiragana: "そ",
        pronounce: "/audio/hiragana/so.mp3",
        difficulty: 2,
        category: "consonant",
      },
    ],
    "ta-line": [
      {
        romaji: "ta",
        hiragana: "た",
        pronounce: "/audio/hiragana/ta.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "chi",
        hiragana: "ち",
        pronounce: "/audio/hiragana/chi.mp3",
        difficulty: 3,
        category: "special",
      },
      {
        romaji: "tsu",
        hiragana: "つ",
        pronounce: "/audio/hiragana/tsu.mp3",
        difficulty: 4,
        category: "special",
      },
      {
        romaji: "te",
        hiragana: "て",
        pronounce: "/audio/hiragana/te.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "to",
        hiragana: "と",
        pronounce: "/audio/hiragana/to.mp3",
        difficulty: 2,
        category: "consonant",
      },
    ],
    "na-line": [
      {
        romaji: "na",
        hiragana: "な",
        pronounce: "/audio/hiragana/na.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "ni",
        hiragana: "に",
        pronounce: "/audio/hiragana/ni.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "nu",
        hiragana: "ぬ",
        pronounce: "/audio/hiragana/nu.mp3",
        difficulty: 3,
        category: "consonant",
      },
      {
        romaji: "ne",
        hiragana: "ね",
        pronounce: "/audio/hiragana/ne.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "no",
        hiragana: "の",
        pronounce: "/audio/hiragana/no.mp3",
        difficulty: 2,
        category: "consonant",
      },
    ],
    "ha-line": [
      {
        romaji: "ha",
        hiragana: "は",
        pronounce: "/audio/hiragana/ha.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "hi",
        hiragana: "ひ",
        pronounce: "/audio/hiragana/hi.mp3",
        difficulty: 3,
        category: "consonant",
      },
      {
        romaji: "fu",
        hiragana: "ふ",
        pronounce: "/audio/hiragana/fu.mp3",
        difficulty: 3,
        category: "special",
      },
      {
        romaji: "he",
        hiragana: "へ",
        pronounce: "/audio/hiragana/he.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "ho",
        hiragana: "ほ",
        pronounce: "/audio/hiragana/ho.mp3",
        difficulty: 2,
        category: "consonant",
      },
    ],
    "ma-line": [
      {
        romaji: "ma",
        hiragana: "ま",
        pronounce: "/audio/hiragana/ma.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "mi",
        hiragana: "み",
        pronounce: "/audio/hiragana/mi.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "mu",
        hiragana: "む",
        pronounce: "/audio/hiragana/mu.mp3",
        difficulty: 3,
        category: "consonant",
      },
      {
        romaji: "me",
        hiragana: "め",
        pronounce: "/audio/hiragana/me.mp3",
        difficulty: 2,
        category: "consonant",
      },
      {
        romaji: "mo",
        hiragana: "も",
        pronounce: "/audio/hiragana/mo.mp3",
        difficulty: 2,
        category: "consonant",
      },
    ],
    "ya-line": [
      {
        romaji: "ya",
        hiragana: "や",
        pronounce: "/audio/hiragana/ya.mp3",
        difficulty: 2,
        category: "consonant",
      },
      null,
      {
        romaji: "yu",
        hiragana: "ゆ",
        pronounce: "/audio/hiragana/yu.mp3",
        difficulty: 2,
        category: "consonant",
      },
      null,
      {
        romaji: "yo",
        hiragana: "よ",
        pronounce: "/audio/hiragana/yo.mp3",
        difficulty: 2,
        category: "consonant",
      },
    ],
    "ra-line": [
      {
        romaji: "ra",
        hiragana: "ら",
        pronounce: "/audio/hiragana/ra.mp3",
        difficulty: 3,
        category: "consonant",
      },
      {
        romaji: "ri",
        hiragana: "り",
        pronounce: "/audio/hiragana/ri.mp3",
        difficulty: 3,
        category: "consonant",
      },
      {
        romaji: "ru",
        hiragana: "る",
        pronounce: "/audio/hiragana/ru.mp3",
        difficulty: 3,
        category: "consonant",
      },
      {
        romaji: "re",
        hiragana: "れ",
        pronounce: "/audio/hiragana/re.mp3",
        difficulty: 3,
        category: "consonant",
      },
      {
        romaji: "ro",
        hiragana: "ろ",
        pronounce: "/audio/hiragana/ro.mp3",
        difficulty: 3,
        category: "consonant",
      },
    ],
    "wa-line": [
      {
        romaji: "wa",
        hiragana: "わ",
        pronounce: "/audio/hiragana/wa.mp3",
        difficulty: 2,
        category: "consonant",
      },
      null,
      null,
      null,
      {
        romaji: "wo",
        hiragana: "を",
        pronounce: "/audio/hiragana/wo.mp3",
        difficulty: 4,
        category: "special",
      },
    ],
    n: [
      {
        romaji: "n",
        hiragana: "ん",
        pronounce: "/audio/hiragana/n.mp3",
        difficulty: 3,
        category: "special",
      },
    ],
  },
  voiced: {
    "ga-line": [
      {
        romaji: "ga",
        hiragana: "が",
        pronounce: "/audio/hiragana/ga.mp3",
        difficulty: 3,
        category: "voiced",
      },
      {
        romaji: "gi",
        hiragana: "ぎ",
        pronounce: "/audio/hiragana/gi.mp3",
        difficulty: 3,
        category: "voiced",
      },
      {
        romaji: "gu",
        hiragana: "ぐ",
        pronounce: "/audio/hiragana/gu.mp3",
        difficulty: 3,
        category: "voiced",
      },
      {
        romaji: "ge",
        hiragana: "げ",
        pronounce: "/audio/hiragana/ge.mp3",
        difficulty: 3,
        category: "voiced",
      },
      {
        romaji: "go",
        hiragana: "ご",
        pronounce: "/audio/hiragana/go.mp3",
        difficulty: 3,
        category: "voiced",
      },
    ],
    "za-line": [
      {
        romaji: "za",
        hiragana: "ざ",
        pronounce: "/audio/hiragana/za.mp3",
        difficulty: 3,
        category: "voiced",
      },
      {
        romaji: "ji",
        hiragana: "じ",
        pronounce: "/audio/hiragana/ji.mp3",
        difficulty: 4,
        category: "voiced",
      },
      {
        romaji: "zu",
        hiragana: "ず",
        pronounce: "/audio/hiragana/zu.mp3",
        difficulty: 3,
        category: "voiced",
      },
      {
        romaji: "ze",
        hiragana: "ぜ",
        pronounce: "/audio/hiragana/ze.mp3",
        difficulty: 3,
        category: "voiced",
      },
      {
        romaji: "zo",
        hiragana: "ぞ",
        pronounce: "/audio/hiragana/zo.mp3",
        difficulty: 3,
        category: "voiced",
      },
    ],
    "da-line": [
      {
        romaji: "da",
        hiragana: "だ",
        pronounce: "/audio/hiragana/da.mp3",
        difficulty: 3,
        category: "voiced",
      },
      {
        romaji: "ji",
        hiragana: "ぢ",
        pronounce: "/audio/hiragana/dji.mp3",
        difficulty: 5,
        category: "voiced",
      },
      {
        romaji: "dzu",
        hiragana: "づ",
        pronounce: "/audio/hiragana/dzu.mp3",
        difficulty: 5,
        category: "voiced",
      },
      {
        romaji: "de",
        hiragana: "で",
        pronounce: "/audio/hiragana/de.mp3",
        difficulty: 3,
        category: "voiced",
      },
      {
        romaji: "do",
        hiragana: "ど",
        pronounce: "/audio/hiragana/do.mp3",
        difficulty: 3,
        category: "voiced",
      },
    ],
    "ba-line": [
      {
        romaji: "ba",
        hiragana: "ば",
        pronounce: "/audio/hiragana/ba.mp3",
        difficulty: 3,
        category: "voiced",
      },
      {
        romaji: "bi",
        hiragana: "び",
        pronounce: "/audio/hiragana/bi.mp3",
        difficulty: 3,
        category: "voiced",
      },
      {
        romaji: "bu",
        hiragana: "ぶ",
        pronounce: "/audio/hiragana/bu.mp3",
        difficulty: 3,
        category: "voiced",
      },
      {
        romaji: "be",
        hiragana: "べ",
        pronounce: "/audio/hiragana/be.mp3",
        difficulty: 3,
        category: "voiced",
      },
      {
        romaji: "bo",
        hiragana: "ぼ",
        pronounce: "/audio/hiragana/bo.mp3",
        difficulty: 3,
        category: "voiced",
      },
    ],
    "pa-line": [
      {
        romaji: "pa",
        hiragana: "ぱ",
        pronounce: "/audio/hiragana/pa.mp3",
        difficulty: 4,
        category: "voiced",
      },
      {
        romaji: "pi",
        hiragana: "ぴ",
        pronounce: "/audio/hiragana/pi.mp3",
        difficulty: 4,
        category: "voiced",
      },
      {
        romaji: "pu",
        hiragana: "ぷ",
        pronounce: "/audio/hiragana/pu.mp3",
        difficulty: 4,
        category: "voiced",
      },
      {
        romaji: "pe",
        hiragana: "ぺ",
        pronounce: "/audio/hiragana/pe.mp3",
        difficulty: 4,
        category: "voiced",
      },
      {
        romaji: "po",
        hiragana: "ぽ",
        pronounce: "/audio/hiragana/po.mp3",
        difficulty: 4,
        category: "voiced",
      },
    ],
  },
};
